### ISSUE TITLE
nga的怎么404了，昨天还好好的

### ISSUE THREAD

**Issue by XueMeijing** [TomoeMami/S1PlainTextBackup#2]
这都能举报？

**Comment by TomoeMami** [comment]
我会不定期手动清理repo，将过期的文档移动到[另一个归档repo](https://github.com/TomoeMami/S1PlainTextArchive2021)中，你要找的应该是[这个](https://github.com/TomoeMami/S1PlainTextArchive2021/blob/master/a%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E7%9A%84%E5%B8%96%E5%AD%90/2026293-01%5B%E6%9D%A5%E8%87%AANGA%E7%9A%84%E5%A4%A7%E7%93%9C%5D.md)

**Comment by TomoeMami** [comment]
更新了旧存档帖子分类文件夹，现在在[这个地方](https://github.com/TomoeMami/S1PlainTextArchive2021/blob/master/%E5%A4%96%E9%87%8E/2026293-01%5B%E6%9D%A5%E8%87%AANGA%E7%9A%84%E5%A4%A7%E7%93%9C%5D.md)
