### ISSUE TITLE
B49 未自动加入 `RefreshingData.json`

### ISSUE THREAD

**Issue by bybybybyb** [TomoeMami/S1PlainTextBackup#4]
还是我理解有误，需要手动加？

**Comment by TomoeMami** [comment]
因为一些原因，存在部分帖子未录入/提前结束存档，已手动修复以下帖子：
2038816 【明日方舟】国服6号楼丨万众期待 肉鸽二期  
2035765 新生·原神综合讨论专楼（禁止新开讨论）
2045381 【B49】VUP综合讨论楼  
2018062 ケーキアツアツ 
2037235 【兎田ぺこら】野兔子日记楼（自用）22：00 生日待机
2037125 原神（多平台）攻略讨论专楼#4（禁止新开讨论）  
2041774 《碧蓝航线》四号楼|
