### ISSUE TITLE
“笑死了，来自泥黄色论坛的地狱笑话”怎么归档了

### ISSUE THREAD

**Issue by GoblinScarecrow** [TomoeMami/S1PlainTextBackup#5]
在[S1PlainTextArchive2022](https://github.com/TomoeMami/S1PlainTextArchive2022)也找不到

**Comment by TomoeMami** [comment]
无法访问的帖子会创建一个包含ID且名字为空的文件夹，内有一个同名md文件。

在被手动挪至archive repo之前，都会保留在对应分目录内。

具体到此帖子，路径为：https://github.com/TomoeMami/S1PlainTextBackup/tree/master/外野/2054357%5B笑死了，来自泥黄色论坛的地狱笑话%5D

**Comment by GoblinScarecrow** [comment]
@TomoeMami 谢谢
