### ISSUE TITLE
旧备份请求补档

### ISSUE THREAD

**Issue by Drgiceake** [TomoeMami/S1PlainTextBackup#6]
gitee.com/TomoeMami/S1PlainTextBackup/blob/master/外野/1889771[我发现我还是低估a岛了]-01
这个备份在gitee上被和谐，在github上没有找到20年之前的备份，请问旧备份是否可以重新上传？

**Comment by TomoeMami** [comment]
https://github.com/TomoeMami/S1PlainTextArchive2021/blob/master/%E5%A4%96%E9%87%8E%E5%85%B6%E4%BB%96/1889771-01%5B%E6%88%91%E5%8F%91%E7%8E%B0%E6%88%91%E8%BF%98%E6%98%AF%E4%BD%8E%E4%BC%B0a%E5%B2%9B%E4%BA%86%5D.md

**Comment by TomoeMami** [comment]
更新了旧存档帖子分类文件夹，现在在[这个地方](https://github.com/TomoeMami/S1PlainTextArchive2021/blob/master/%E5%A4%96%E9%87%8E/1889771-01%5B%E6%88%91%E5%8F%91%E7%8E%B0%E6%88%91%E8%BF%98%E6%98%AF%E4%BD%8E%E4%BC%B0a%E5%B2%9B%E4%BA%86%5D.md)
